services:
  - type: web
    name: tibg-sport-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --threads 2 --worker-class sync --bind 0.0.0.0:$PORT
    envVars:
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: PORT
        value: 10000
