services:
  - type: web
    name: tibg-sport-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HuggingFace__ApiKey
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:5000